/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import gameScene3D from "./scripts/gameScene3D"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedauto";
    static screenMode:string="horizontal";
    static alignV:string="top";
    static alignH:string="center";
    static startScene:any="view/gameScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("scripts/gameScene3D.ts",gameScene3D);
    }
}
GameConfig.init();