/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.view {
    export class gameSceneUI extends View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/gameScene");
        }
    }
    REG("ui.view.gameSceneUI",gameSceneUI);
}