/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module jiexunsdk.JieXunRes.gameScene {
    export class homeViewUI extends View {
		public ani1:Laya.FrameAnimation;
		public ani2:Laya.FrameAnimation;
		public bgSkin:Laya.Image;
		public topPanel:Laya.Box;
		public bottomui:Laya.Box;
		public btnPlay:Laya.Button;
		public appBanner:Laya.Button;
		public gameList:Laya.Box;
		public upList:Laya.List;
		public initLeve:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("JieXunRes/gameScene/homeView");
        }
    }
    REG("jiexunsdk.JieXunRes.gameScene.homeViewUI",homeViewUI);
    export class loadViewUI extends View {
		public lblPres:Laya.Label;
		public barPres:Laya.ProgressBar;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("JieXunRes/gameScene/loadView");
        }
    }
    REG("jiexunsdk.JieXunRes.gameScene.loadViewUI",loadViewUI);
    export class overGameUI extends View {
		public wxBanner:Laya.Image;
		public reGame:Laya.Button;
		public backHome:Laya.Button;
		public maxScroe:Laya.FontClip;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("JieXunRes/gameScene/overGame");
        }
    }
    REG("jiexunsdk.JieXunRes.gameScene.overGameUI",overGameUI);
    export class rcontinueGameUI extends View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("JieXunRes/gameScene/rcontinueGame");
        }
    }
    REG("jiexunsdk.JieXunRes.gameScene.rcontinueGameUI",rcontinueGameUI);
}