/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import homeView from "./jiexun/main/view/homeView"
import loading from "./jiexun/main/view/loading"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="horizontal";
    static alignV:string="top";
    static alignH:string="center";
    static startScene:any="JieXunRes/gameScene/homeView.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("jiexun/main/view/homeView.ts",homeView);
        reg("jiexun/main/view/loading.ts",loading);
    }
}
GameConfig.init();